name: Publish

on:
  workflow_run:
    workflows: ["Push or PR"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') && startsWith(github.ref, 'refs/tags/v') }}
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
